### ISSUE TITLE
Add native habitat/range to each ambassador

### ISSUE THREAD

**Issue by pjeweb** [alveusgg/data#20]
e.g. Toaster Strudel -> Australia and New Guinea (forests, scrublands, and deserts)

**Comment by itsjayway** [comment]
hey @pjeweb, is this issue still available? i wanted to ask where should i source the info from for each ambassador. thank you in advance

**Comment by pjeweb** [comment]
> hey @pjeweb, is this issue still available? 

sure. we would need a concept for the extension and website to make it usable also, but adding the data here would be great already

> i wanted to ask where should i source the info from for each ambassador

I mean, I'm no expert on animal things. I would probably google/bing search until I find a reasonable source. Possibly wikipedia. It would be great if you keep a reference of each source in the code (as a code comment or so).
